from . import detection
from . import segmentation
from . import segmentation3d
from . import classification3d
from . import fusion
from .alexnet import *
from .densenet import *
from .googlenet import *
from .inception import *
from .mnasnet import *
from .mobilenet import *
from .resnet import *
from .shufflenetv2 import *
from .squeezenet import *
from .vgg import *
from .res2net_v1b import *
from .resnet3d import *
